// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lexysgkfjuxemhsbqmah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleHlzZ2tmanV4ZW1oc2JxbWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjMwNDksImV4cCI6MjA2NTkzOTA0OX0.ryN3Ul62_l5pSytltBSoaQ13QwfO9SO3ehEFLlju064";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);