// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytxlpivdqnjraaknksqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eGxwaXZkcW5qcmFha25rc3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTY5ODgsImV4cCI6MjA2NjEzMjk4OH0.FbKbdGKCBTarCvLf565kR2U2_6_VZnUjDxY98cWvDwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);